version: "3.8"
services:
  dev-db:
    image: postgres:16.11-alpine3.23
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=value
      - POSTGRES_PASSWORD=testing
      - POSTGRES_NAME=dev-db